### PR TITLE
Develop

### LINKED ISSUE #249: custom integration 'mydolphin_plus' is setting the battery_icon which has been deprecated. This will stop working in Home Assistant 2026.8
This may be a new error with HA 2025.8 or it's one I haven't noticed before for previous releases.

`2025-08-12 18:35:45.936 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'mydolphin_plus' is setting the battery_icon which has been deprecated. Integration mydolphin_plus should implement a sensor instead with a correct device class and link it to the same device. This will stop working in Home Assistant 2026.8, please create a bug report at https://github.com/sh00t2kill/dolphin-robot/issues`

### LINKED ISSUE #250: Light entity state vs activity property
Detected that custom integration 'mydolphin_plus' is setting state directly. Entity vacuum.{entity_name} (<class 'custom_components.mydolphin_plus.vacuum.MyDolphinPlusLightEntity'>) should implement the 'activity' property and return its state using the VacuumActivity enum. This will stop working in Home Assistant 2026.1

### PR DESCRIPTION
**Pull request by elad-bar**
## v1.0.23

- Remove navigate service (`mydolphin_plus.navigate`)
- Remove exit navigation service (`mydolphin_plus.exit_navigation`)
- Add Remote entity allowing to control and turn off control using a virtual joystick
  - Provides virtual joystick interface for manual robot navigation
  - Supports 5 joystick directions: stop, forward, backward, left, right
  - Uses standard Home Assistant remote entity with activity feature
  - Replaces the old custom navigate services with native HA functionality
  - Enables precise manual control of robot movement via UI or automation

## v1.0.22

- Fix deprecated `battery_icon` property in vacuum entity (resolves [#249](https://github.com/sh00t2kill/dolphin-robot/issues/249))
- Add dedicated battery sensor with proper device class (`SensorDeviceClass.BATTERY`)
- Remove hardcoded battery level from vacuum entity
- Fix deprecated vacuum state constants (STATE_DOCKED, STATE_CLEANING, STATE_ERROR, STATE_RETURNING)
- Replace deprecated constants with VacuumActivity enum for Home Assistant 2026.1 compatibility
- Update imports in coordinator.py and system_details.py to use VacuumActivity
- Fix vacuum entity to use activity property instead of direct state setting (resolves [#250](https://github.com/sh00t2kill/dolphin-robot/issues/250))
- Add VacuumActivity enum support for proper vacuum state management
- Fix API response handling to prevent 'str' object has no attribute 'get' error
- Add type checking for login API response to handle string responses gracefully
- Update manifest.json with integration metadata and version bump
- Resolves deprecation warnings for Home Assistant 2026.8 compatibility

Added to troubleshooting README details of how to address OTP issue for issue #199

### CODE REVIEW

**Comment by elad-bar** [comment]
@sh00t2kill - long time, hope all is good.

i added fixes and new feature for remote control instead of navigation service, on top of that aligned version,
as I udnerstand you no longer have a pool, can you pls change the policy for this repo so i will not wait for your additional approval so i will be able to release versions.

thanks

**Review by sh00t2kill — APPROVED** [review]
